# Generated by Django 4.1.3 on 2022-12-27 11:53

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="TgUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tg_chat_id", models.IntegerField(verbose_name="id чата")),
                (
                    "tg_user_id",
                    models.IntegerField(verbose_name="id пользователя Телеграмм"),
                ),
                (
                    "tg_username",
                    models.CharField(
                        max_length=32,
                        validators=[django.core.validators.MinLengthValidator(5)],
                        verbose_name="Имя пользователя Телеграмм",
                    ),
                ),
                (
                    "verification_code",
                    models.CharField(
                        max_length=10, unique=True, verbose_name="Верификационный код"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователь API",
                    ),
                ),
            ],
        ),
    ]
